### ISSUE TITLE
Use Rails helpers 

### ISSUE THREAD

**Issue by jpbarela** [madeleinemarie/Mile-High-Music#14]
This code https://github.com/madeleinemarie/Mile-High-Music/blob/master/app/controllers/playlists_controller.rb#L6-L8 comes from Sinatra but Rails provides a better way to parse JSON

**Comment by jpbarela** [comment]
Assigned to TEAM

**Comment by fishcharlie** [comment]
Pretty sure @madeleinemarie finished this. Could be wrong tho.

**Comment by madeleinemarie** [comment]
@jpbarela @fishcharlie I refactored the entire Playlist Controller so the issue should be solved.
